version: '3'

services:
  flask-app:
    container_name: flask-app-container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  kafka:
    container_name: kafka-container
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka  # Adjust as needed
      KAFKA_RETENTION_MS: 300000  # 1 day in milliseconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    container_name: zookeeper-container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  airflow:
    image: apache/airflow:latest
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./airflow_home/dags:/usr/local/airflow/dags  # Adjusted volume mapping
      - ./airflow_home:/usr/local/airflow  # Mount AIRFLOW_HOME directory
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow webserver -p 8080"
    depends_on:
      - flask-app
